<?php require_once("db.class.php");
	$reportId=$_GET['reportId'];
	$albumin=$_GET['albumin'];
	$phosphates=$_GET['phosphates'];
	$sugar_fasting=$_GET['sugar_fasting'];
	$sugar_PP=$_GET['sugar_PP'];
	$sugar_random=$_GET['sugar_random'];
	$WBC_puss_cells=$_GET['WBC_puss_cells'];
	$RBC=$_GET['RBC'];
	$epithelial_cells=$_GET['epithelial_cells'];
	$CASTS=$_GET['CASTS'];
	$CRYSTALS=$_GET['CRYSTALS'];
	$colour=$_GET['colour'];
	$appearance=$_GET['appearance'];
	$sediment=$_GET['sediment'];
	$ph_reaction=$_GET['ph_reaction'];
	$specific_gravity=$_GET['specific_gravity'];
	$bile_salts=$_GET['bile_salts'];
	$bile_pigments=$_GET['bile_pigments'];
	$urobilinogen=$_GET['urobilinogen'];
	$KETONE=$_GET['KETONE'];
	$NITRITE=$_GET['NITRITE'];
	$ketone_bodies_acetone=$_GET['ketone_bodies_acetone'];
	$chyle=$_GET['chyle'];
	$bence_zence_protein=$_GET['bence_zence_protein'];
	$occult_blood=$_GET['occult_blood'];
	$pregnancy_test=$_GET['pregnancy_test'];
	$sql = "UPDATE `urine_examination` SET `albumin` = '".$albumin."', `phosphates` = '".$phosphates."', `sugar(Fasting)` = '".$sugar_fasting."', `sugar(P.P)` = '".$sugar_PP."', `sugar(random)` = '".$sugar_random."', `wbc_puss_cells` = '".$WBC_puss_cells."', `rbc` = '".$RBC."', `epithelial_cells` = '".$epithelial_cells."', `casts` = '".$CASTS."', `crystals` = '".$CRYSTALS."', `colour` = '".$colour."', `appearance` = '".$appearance."', `sediment` = '".$sediment."', `ph_reaction` = '".$ph_reaction."', `specific_gravity` = '".$specific_gravity."', `bile_salts` = '".$bile_salts."', `bile_pigments` = '".$bile_pigments."', `urobilinogen` = '".$urobilinogen."', `ketone` = '".$KETONE."', `nitrite` = '".$NITRITE."', `ketone_bodies_acetone` = '".$ketone_bodies_acetone."', `chyle` = '".$chyle."', `bence_zence_protein` = '".$bence_zence_protein."', `occult_blood` = '".$occult_blood."', `pregnancy_test` = '".$pregnancy_test."' WHERE `urine_examination`.`id` = $reportId;";
	mysqli_query($CON, $sql);
	echo "urine examination report updated!";
?>